hash-format = "sha256"

[[files]]
file = "config/artifacts/client.toml"
hash = "3921700655db2af439702410ce0f4771955fa426b8b184ccb569721063da2a70"

[[files]]
file = "config/artifacts/general.toml"
hash = "adf28da3015f3eb102da2e6d208233db280c08b3a005cbe65d86d7d64135f31d"

[[files]]
file = "config/artifacts/items.toml"
hash = "4ad2b5325a9ddd32792b0cca532ab88914ae0c85aef8f5f56db8f5e75609bc28"

[[files]]
file = "config/backpacked.augments.toml"
hash = "02a0fadf11aa58e9f43f54987e312c213bdc36eb78f907c53b0d76761341b341"

[[files]]
file = "config/backpacked.backpack.toml"
hash = "b5b2060f875858daed883c103f437374d201b7059a28f046f4cc97b205c56150"

[[files]]
file = "config/backpacked.client.toml"
hash = "f5f2119a74e1f04405ab116f3b3dfdcceb2051c433743e8379f3d7f1d8f77f65"

[[files]]
file = "config/backpacked.pickpocketing.toml"
hash = "c57978cacb2b994b9a89632dca992949e7636e70698f9a98e1d2737f142ac4ea"

[[files]]
file = "config/backpacked.wandering_trader.toml"
hash = "50dacc67d9c57336f4af3322bd4458b0cc8c8135517408a5c7876e74771af26e"

[[files]]
file = "config/charmofundying-server.toml"
hash = "4a4687d0d8eb4ef48c97044bf1e7dc0c69475a9d95331ceb0d1fde3495d17ba4"

[[files]]
file = "config/create-client.toml"
hash = "e20f6769fd946b918f24cfd54a422a599faa43394ee9a33012e645102a366da3"

[[files]]
file = "config/create-common.toml"
hash = "2e77b1d93b40ce3f381ad7eb2a9e6d7148de917518be5c2616939a4369c4b140"

[[files]]
file = "config/create-server-1.toml.bak"
hash = "d87d179512584a76999032263c4403b86c8f0d08b129e2b15a09082c3b286211"

[[files]]
file = "config/create-server.toml"
hash = "d063982581108b8c7ed6c670c4f4a302abe39be7bfeb565de96b8d9d880426cd"

[[files]]
file = "config/create_aquatic_ambitions-server.toml"
hash = "501d4be5fa528302ab173dd86708e570935285505f44ef1fd0694b8cd60eee58"

[[files]]
file = "config/create_dragons_plus-client.toml"
hash = "cf30f0e99ef65fe80e80481bf9aaafefdbbf97adb84c0c3611ac2d9ca3cf8a28"

[[files]]
file = "config/create_dragons_plus-common.toml"
hash = "5b1b6397fdc6e5e8f26527b78c9386a34b143e180efca6d086387778b79fbb65"

[[files]]
file = "config/create_dragons_plus-server.toml"
hash = "06c232854b6d18ea18bd9bbbed7a0317c0113aad12734066a46a1d9d28278520"

[[files]]
file = "config/create_enchantment_industry-client.toml"
hash = "f1c6a25f81ec0f112e431b9064088e641c37b33a1aa16eed2bc4d03884c2b39c"

[[files]]
file = "config/create_enchantment_industry-server.toml"
hash = "b62b515186f1afad738083a1eb0b4d1a12b3bcd2d530d6de64a5fd94b44c83a1"

[[files]]
file = "config/create_jetpack-client.toml"
hash = "89094f05746ba946d303ca7fd7888094c34165b4af507317e081b6c9b5f7ecc3"

[[files]]
file = "config/create_jetpack-common.toml"
hash = "1177996d40fc3be7b7716d2594874ac48b64d890ac82a88b41c88aff89a02567"

[[files]]
file = "config/createaddition-common.toml"
hash = "0441e89a64a3730006d3dde2e1fe81a25f9af4fcb1fd08c9f956b00e56c50650"

[[files]]
file = "config/creategoggles-client.toml"
hash = "a7388317bf092e58a7a4aee6bf6ee22f6a2ae5adaabff30e6ca07b3260eeee42"

[[files]]
file = "config/creategoggles-common.toml"
hash = "674d0b72918889f050aeac9d59890f35330c833df1c93b35dd4a797020a43c40"

[[files]]
file = "config/curios-client.toml"
hash = "8af475d222d452c40b548db89c8956f3e4d1e2aaf729464e3065f029936b3e0d"

[[files]]
file = "config/curios-common.toml"
hash = "9f00a6b9904cf63a36c0c72f8346642962d538aaa78b59943b9de60dda82e6d0"

[[files]]
file = "config/curios-server.toml"
hash = "1a3bee95a96f082b8e97cccbce30c1efe1352b616c78e06d5884fd4475668add"

[[files]]
file = "config/enchanted-client.toml"
hash = "c8a191c1d968e5f928a3ce87f7efa848ef5e766d31a1687faf582ce068e03f5c"

[[files]]
file = "config/enchanted-server.toml"
hash = "fb98c3ccfa78d866555d129887ef9618f1a3f0fe6e15a8e6794e81a745b919bf"

[[files]]
file = "config/ferritecore-mixin.toml"
hash = "1356f9d52b2dcb2afa5a593e53c286d9c1c3778a6f8b1cf761953b185b7dce78"

[[files]]
file = "config/flywheel-client.toml"
hash = "c83e873ce093460a6b909f2a2bf8345fc9cd2699043731c02ff04d72dcb4d7cc"

[[files]]
file = "config/fml.toml"
hash = "1ac1fd9694773ef1ec8af42c9cc8a908a1b618fa6fb6031c27305383e97f70c7"

[[files]]
file = "config/friendsandfoes.json"
hash = "5378186838edcf828c352a47b0ea7e5f87efcadc7230eef08dc7d2c9ed6d27c7"

[[files]]
file = "config/item_obliterator.json5"
hash = "554edb2ce54ce7f21ebede3d968d04551fc64fe1d4de5bdc30876dd5ebdf96b6"

[[files]]
file = "config/jei-server.toml"
hash = "702acd04d99445bce659d04fcc488e1a98c8a803983c31ae262b0f3a47fdc8d3"

[[files]]
file = "config/jei/blacklist.json"
hash = "b4174dc6e985aa90be5002c14e94b956d8d586683c44b7b6710c44d08fb13648"

[[files]]
file = "config/jei/ingredient-list-mod-sort-order.ini"
hash = "2c76d7fdd9341d02e31bb86e1a56eb2eabce77176c7c239d9a1184ab7ad2020a"

[[files]]
file = "config/jei/ingredient-list-type-sort-order.ini"
hash = "dbe59536c485906f085a216661baffcd9dcb0c704e0c2c210da6c32910fb8f7b"

[[files]]
file = "config/jei/jei-client.ini"
hash = "f6841387ba118885299e6fe6574daaa62ad5adcf4e73f851ec2e9f8977ea066d"

[[files]]
file = "config/jei/jei-colors.ini"
hash = "755f199a3868224bdccb2a8ffd8f1a4eb2d96140757f444ba31f8d677a66034f"

[[files]]
file = "config/jei/jei-debug.ini"
hash = "960b16c7af6d62bbe7b58fb52216a8a15771bddecbeefab49a8614b7ca86dcbd"

[[files]]
file = "config/jei/jei-mod-id-format.ini"
hash = "6a91c09d1cabc1980d90ab102a03ec58c0551213ab16a459b599d768b334d054"

[[files]]
file = "config/jei/recipe-category-sort-order.ini"
hash = "1253a7981ca45d27875557ab45d0954bbee934ea365bf6f77cd3860ad39c0ae5"

[[files]]
file = "config/jei/world/local/New_World__3/lookupHistory.json"
hash = "00f941c21f71eed0c25cff642c6264a8044b5481172f778f9c21cec5e5810d94"

[[files]]
file = "config/jei/world/local/New_World__4/lookupHistory.json"
hash = "184781bce219024c6e5b239ddf5dadcb943cae959416f028fb8e686cf4d8660c"

[[files]]
file = "config/jei/world/local/New_World__5/lookupHistory.json"
hash = "aae4040daabec1d5a8738c1b353a6a8abdf6ab06f7f57eb94743f377f94f7bf7"

[[files]]
file = "config/jei/world/server/Psychokring_bf9eaea6/bookmarks.json"
hash = "6b1e433f078727d9021dde13bb3b68b0df21eaca852e31cb836c25592e8d4041"

[[files]]
file = "config/jei/world/server/Psychokring_bf9eaea6/lookupHistory.json"
hash = "753e06bf674988f5532ba099da3ca623b49e74acdf37e39a692fa283be424b44"

[[files]]
file = "config/keepcuriosinventory-common.toml"
hash = "8a80fb35a46aa7fa40d6c4e4e64bb4b5c1bcb3c260024f4277a4022276f4e9e1"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/lootr-client.toml"
hash = "d196b5c4f46f5ea21ff38a78bcda94834b48ef5554473bcab1fd3bb9effe3220"

[[files]]
file = "config/lootr-common.toml"
hash = "0092d1efe145a764003908c75ca6d305435fd322edf88a14e4d2651c77c408dd"

[[files]]
file = "config/modernfix-common.toml"
hash = "72ca2bcea2a9946a3a54842f14eff6f7b47d8fc96ef497c1b56406643b153fd7"

[[files]]
file = "config/modernfix-mixins.properties"
hash = "d1d882ced63b3dbee97047dc792fc000bdb53fdd956ee1121068751d0303e51b"

[[files]]
file = "config/modopedia-server.toml"
hash = "45dcd71cbbf1730777f0f10d36a45ad16f2003db26d811ac5b58fa52dfa2e6f8"

[[files]]
file = "config/necronomicon.json5"
hash = "f97fc5ae7dd7d312e86ecddf2e4491fee3e3a16b7a26cbb3aa078fdd3255c4df"

[[files]]
file = "config/neoforge-client.toml"
hash = "d58d93e2c429410d0abf25507d1679f732e1023b03bb52414348efcf5cf3ddb0"

[[files]]
file = "config/neoforge-common.toml"
hash = "fe878a2717a145cd890621eac5b3be1e1fd656f7ff9abc6e8d53f670d37474c4"

[[files]]
file = "config/neoforge-server.toml"
hash = "b1e3b38d612295f8d9dfa0fbdb538a992b7a1a3b7a766c491b4e9fdf3823396f"

[[files]]
file = "config/platform-client.toml"
hash = "127580e6a7872bc97b55280e53f0a11bce8a655b8fe2ded66a88ecde8389bab1"

[[files]]
file = "config/ponder-client.toml"
hash = "55affffe67e84dfe11e590769e235aee999b77f9484a3adf7ee8247a9f3d35ba"

[[files]]
file = "config/relics.yaml"
hash = "4411078ac8d2107482e0f717576b1d9e1fa6c0938d11135a2541f4d8c2518278"

[[files]]
file = "config/reliquified_twilight_forest/general.yaml"
hash = "30d073baf7960f541f89b3936b0cddc5e7f4b76407e2a44b832659e6c2bcaf0d"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "0015bcf83bd965cf9bc4c195ad3c0684e60fd2586126cf47cff7999cfb0a0b40"

[[files]]
file = "config/sodium-mixins.properties"
hash = "b627c4456e6fa0bc4b5f85e2f1cd949faedae3cb9afdaf2a5f52e6f3b6ae1f01"

[[files]]
file = "config/sodium-options.json"
hash = "00c7dd465e12693baeb0f9844848eb087f627d98827df51111b080af462d7d73"

[[files]]
file = "config/tombstone-client.toml"
hash = "a5d75697b44476b81a5abdfa2686a9300d6e619a2573a84541de1639874a4487"

[[files]]
file = "config/tombstone-common.toml"
hash = "79af0b364c3ac2cd80f29bb3fe2fb3f2fde4712a5599ef3aa9600a6aafb49e6a"

[[files]]
file = "config/trade_cycling-client.toml"
hash = "b1f7ad749bc197d88af203010ef49252a3492ccf13ca80020eb8a76d5740b590"

[[files]]
file = "config/twilightforest-client-1.toml.bak"
hash = "ffc2211914005f7dd791908435e35e305f70eb91a07094740a63a639b2a8489a"

[[files]]
file = "config/twilightforest-client.toml"
hash = "e373d9c757bf4be6c1bad1df131458e0c6e6b2c17a9962150b4e658117a4f35a"

[[files]]
file = "config/twilightforest-common.toml"
hash = "0d549a05737b751577752292e1dc8affc5dbe0b5f2592ba08e5de2ee5753b6a7"

[[files]]
file = "config/vanillabackport-client-1.toml.bak"
hash = "49fe6d92a49bb88f4d3dfb14a63e60595ae8c028b4abd671302d759f4373dba4"

[[files]]
file = "config/vanillabackport-client.toml"
hash = "021c02aec7ffcc09d811a218f274f47062eaf77d8ae4ac9ac0897839a88161fa"

[[files]]
file = "config/vanillabackport-common-1.toml.bak"
hash = "102161aa6a555a6e2931d2372404b0902d2fe9a3c2364c84029510204f3c77f6"

[[files]]
file = "config/vanillabackport-common.toml"
hash = "4bad441e716cd909aea6d6a36788d7ee9f17d3a343420866b9397292d2930a5d"

[[files]]
file = "config/xaero/lib/client.cfg"
hash = "43ed9dbfa5b4d6f0f3d2e8c2ced17ad298164b22c68ff11d415257a39b074336"

[[files]]
file = "config/xaero/lib/common.cfg"
hash = "98f698d96a6d21d830a455b4ad045b70516fa63c298021742d8499e7f0366cd2"

[[files]]
file = "config/xaero/lib/profiles/default.cfg"
hash = "34ae854b17d896d7cb853bdc28c27231a3947e91cb9f0991f372846ee3c2a907"

[[files]]
file = "config/xaero/lib/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaero/minimap/client.cfg"
hash = "c0915eff5d1a7905cd1038d646eb9086fd1a29e2f637d53535e4da161de17b9f"

[[files]]
file = "config/xaero/minimap/common.cfg"
hash = "2b49df024c03a369c62a303c72755e7fedeb4f4653ff53a12fd37bd83ccd4ed0"

[[files]]
file = "config/xaero/minimap/default_radar_categories_client.json"
hash = "3c888b22cba252e8f0a974f8c1604bc05109affbf4354ad3b16e71778c4b9774"

[[files]]
file = "config/xaero/minimap/default_radar_categories_server.json"
hash = "a4c652cafa7dea324e5f5cf3b1df46a84e54b6d4f877195857bce55a559c1cfd"

[[files]]
file = "config/xaero/minimap/profiles/default.cfg"
hash = "4ffba4ec814acc4fb64193990f2c797dff9d4d4c33813923f1a443fcc4da9e16"

[[files]]
file = "config/xaero/minimap/profiles/info_display_config/default.cfg.txt"
hash = "184e654fa1fc8ad09943c97c4e65ab78acb5b3cfca22417a831513d1b6d9bbc6"

[[files]]
file = "config/xaero/minimap/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaero/world-map/client.cfg"
hash = "e0701e39b182760039d11c2256be27b35592aba1ba837daec4a55cdb9859baa6"

[[files]]
file = "config/xaero/world-map/common.cfg"
hash = "0c229eb0daf85bd09af51f21eeeb99497a3bd50a825d5ab1ca695fb21bf6cf9d"

[[files]]
file = "config/xaero/world-map/profiles/default.cfg"
hash = "7b24c882801bcc7f0a8aedc625d419f661fa490fa0e9d5ebe39599a1ce2dcbd5"

[[files]]
file = "config/xaero/world-map/server_profiles/default.cfg"
hash = "d438aea41ca41e93697e059f523686935c0add482f6abe96b532bbf10c6ed80a"

[[files]]
file = "config/xaerohud.txt"
hash = "58c9270f258d0b224bb7d0f7c927544d5fbe5f1b8027c820e1e14ecbf48fb88c"

[[files]]
file = "config/xaerominimap-common.txt.backup0"
hash = "771a844d13ab6c2ff99f14b8fd912d02c55a1a4104361692b740c3e596084f6f"

[[files]]
file = "config/xaeropatreon.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/yacl.json5"
hash = "121b93764159be6fb7dab523b29a844e2bb78400ce8c48f52135a097e9b0006e"

[[files]]
file = "config/yyzsbackpack/materials/diamond.json"
hash = "7e43a7abbc51bbc7ff30dcbceee7f9de6b182892269a084a12c54b3627556bfb"

[[files]]
file = "config/yyzsbackpack/materials/gold.json"
hash = "11248df5d13f7b16c3ec26d1dec0fff925a539cf6365aa39d985417e2a7a092a"

[[files]]
file = "config/yyzsbackpack/materials/iron.json"
hash = "a86dce7b2687b98b84d4c742e1ec084e3e35d87c630151845e09917c64089c29"

[[files]]
file = "config/yyzsbackpack/materials/netherite.json"
hash = "e1cb5559dceb93b51747ab562fab2f02feba81e3da775d2f409039fc4e5f73fe"

[[files]]
file = "config/yyzsbackpack/yyzsbackpack.json"
hash = "b3023d06a4ed3c128afbd61ec6f554d1aa46424df86c7f49142c55490c544bfe"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "935a80e462527880c90ab4abba671f1add411c441096d1aaab5855ae98484f1f"
metafile = true

[[files]]
file = "mods/backpacked.pw.toml"
hash = "0dd50b45d3524ea768a42aa50d5d82eb11042d7c56639a5fb0dcf378f05f2284"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "86cf2ae835b8f3d981af2e88a4d19fdc3dc4f5aa3904c6ba30e25d77d3e9fcbb"
metafile = true

[[files]]
file = "mods/charm-of-undying.pw.toml"
hash = "a5a04d39791ce824b7b0b78fd1fa4f08d1584c77c9c52edcb7210439f8917e98"
metafile = true

[[files]]
file = "mods/create-aquatic-ambitions.pw.toml"
hash = "04d77085a95a9c684abed02b1fbdd1b0252c2d440a4f26da84bbbf50a9b5b7d1"
metafile = true

[[files]]
file = "mods/create-curios-jetpack.pw.toml"
hash = "4d4804b4b09a1e8df068f465cca9b07b818ee6d6c2c061269e42b2cea9749be0"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "b4cb9f000ce5f219a468cbc3062314acf6c72c82999720d08a5422d051c617d2"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "979632aae1dad7f82a5a1a34ea1c5844f9584129d4fa5677c28b32cb319b6fd7"
metafile = true

[[files]]
file = "mods/create-goggles.pw.toml"
hash = "9b831e115993c10d0e8b3d187584393685ba0abfaa3ab3ca6ee9dfdf6e1a8e70"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
hash = "ad89085cff15370c0a8bda81c22a3a040204c71f1ee170a458a949295dc219bf"
metafile = true

[[files]]
file = "mods/create-oxidized.pw.toml"
hash = "cde568a867601aaf6b779b6565bf2ed19f127fa1415f8d68f30b25b2dc70de42"
metafile = true

[[files]]
file = "mods/create-ultimate-factory.pw.toml"
hash = "19e09f411c463afb3b7d39678f33b52f718f87923832b697e16676df35c09496"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "779974fc6c7b273a38bd93a26c21c2b8f5e06384516ad8ba29b6bf5fe18514cd"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "7aa0060e5df8631d27a789d73eb57d67c611b95be5bce4175810351e9479ae60"
metafile = true

[[files]]
file = "mods/curios-continuation.pw.toml"
hash = "728964f212cc592a2fc2ae5106e06893a0697568aa9983d164dc112821dc8fc6"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f92e7a06645e41ea1934dc420eb2772edb1708c0d71cb427baef8cf753acb934"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "32078c39569bbb4b33d2d86a09cfc18a9f5b63a11d0ba2b186fd07341e422c92"
metafile = true

[[files]]
file = "mods/enchanted-witchcraft.pw.toml"
hash = "4673c2774e51809fae063e47b483e2c0fde1dc60c5a7431daa8357e1ebbc06d5"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "dff824171060c79b327a4880c2f0546c727a041a489ef3af643ec2dcd9cd0c48"
metafile = true

[[files]]
file = "mods/formations-overworld.pw.toml"
hash = "45285b5b3d52280b267f8fddb8b5b3bf32763c5b27626bb46adb4c6fbb9d54d2"
metafile = true

[[files]]
file = "mods/formations.pw.toml"
hash = "4c74b4ee823da032d8cd4e2cf2e28e22c009a47b57bf4597a2221ede908a97d1"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "dd0153bc05a3ffc8592dfaf35b4e8014127e6e1b352d7c18462d49a1ed7a5035"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "e448ed8448354d972dcd3ef7c46833e58de16147fe947a969538bf80efad6de9"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "89395dd9fcb8ae67889d991207cb95ed7158571c387dde88012853c5fa9ca3fb"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
hash = "aeb82b93a8948a84d4aff642bda7e969ad7d0d3182bff327973035ef11ad5a94"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "2adc7a51ce009ed3e7c1e0d22fd71ad2c152796d8e0ab6cda1447bf89d6404bb"
metafile = true

[[files]]
file = "mods/keepcuriosinventory.pw.toml"
hash = "308541d79e063bc3fe777cf2549b10fd0a88b060a0d036850036d66d187cfe5e"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "3c13beafeb69d23d2a43805cfa3d79b7e458cfb8f9ce603075b84d95da630d4b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3ac8c76f4cb2f1200d60fa2e74108d9cb9355346ddb8a4a735134dfac7b77136"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "964a932d5ea6c63b79b89693438a37d729e205e015500289e272f4d5aba38bde"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "161318b6de204d2528485fe7e401ce522f0be1d62eb5e15b9ac2ba10caf0771a"
metafile = true

[[files]]
file = "mods/modopedia.pw.toml"
hash = "48f62163a8fc70ce7d50e86c62238281fee50864e5356a93a6a866cc7f3e6cfb"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
hash = "6acba5e53610fc3e62bd9641aeaaba056f99248a2d1d86bbf032061a1e408826"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "32f8d722b8e90a4ded120d3cbc7d6718d7bc2ea57a292af725978117710a6490"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "1264a43ce919f188661443bd959cdebb4be04ce70a2965835043c2b18cae730e"
metafile = true

[[files]]
file = "mods/rar-compat.pw.toml"
hash = "68d7d2cbeb93c10f99b3985c96b098aed7dc64f5d08e4855fdd9f37a759f7072"
metafile = true

[[files]]
file = "mods/relics-mod.pw.toml"
hash = "18afbb4fd160f3835d3730a1f3d9e3f299902fbc6da223e0970bc5a77bcc9349"
metafile = true

[[files]]
file = "mods/reliquified-twilight-forest.pw.toml"
hash = "ea80cd43856df236cdfc3f5b2a826e2965eb83d4f35cf465ccbd61c4b5b02bf7"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "aa83553db30adc47f86010f6443340251323a62ee3f9415a0c4332cb6d502419"
metafile = true

[[files]]
file = "mods/sky-villages-forge.pw.toml"
hash = "49293cb0b33f4acd9b12a1ea953532821d001040f5f5010a4de7b5c461d1214c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8d5628a4af0f355519b17bb0c6e5783c30aa78f6aa04b77b3892cd5d7c10af03"
metafile = true

[[files]]
file = "mods/stateobserver.pw.toml"
hash = "322a7defbd55448f14fcf447fd4514156aa6c083fb095a3347aebdf04e10069b"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "0e02e93b9468dca005f7fea385e92612e38bb6807f4dcd64ce7a4b22fac78581"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "b2dd43f9809966eaed8ece9f72ec9ca4f35e8b1d5fd04cb7aa54d847ac9dab91"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "4c00caba57fa2aa18ebf941fbe897ab444252f6baf816f5d1fea9430ac5b3779"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "4dda7b774a3f817a60d467c68654430575f5e68908258e1212371dc171e1363e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "6ece72c173c16cab39e3e30429d49d19f1f88762cd0a351c4ff414d5a3f55891"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "f1665e4f5c0a42d6757bfc7bbbf2d4a23a232302cc78a4ca73f1fc1504ed6441"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "492daa3391b6079b541685db276007b286774bab3b9881505127b7aef6b3f16c"
metafile = true

[[files]]
file = "resourcepacks/baby-mobs.pw.toml"
hash = "25d0c1eb988efa8e79bb1695252d9c382eea999e3d64b199abac87fc7a6d9b7d"
metafile = true
